version: '3.8'

services:
  server:
    build: ./server
    environment:
      - LIVEKIT_HOST=http://host.docker.internal:7880
    ports:
      - "8101:8101"

  client:
    build: ./client
    ports:
      - "8100:8100"
